### ISSUE TITLE
Breaking SVGs

### ISSUE THREAD

**Issue by goodwinchris** [dockyard/narwin-pack#11]
The input code for an svg file is: 
```
<svg viewBox="0 0 34 32">
  <path stroke-width="3.5556" stroke-miterlimit="4" stroke-linecap="square" stroke-linejoin="miter" d="M4.032 4.032l25.243 25.243"></path>
  <path stroke-width="3.5556" stroke-miterlimit="4" stroke-linecap="square" stroke-linejoin="miter" d="M29.746 4.032l-25.243 25.243"></path>
</svg>
```

The exported code onto the page is: 
```
<svg viewBox="0 0 34 32" class="icon-close" aria-label="Close modal">
  <path d="M4.032 4.032l25.243 25.243M29.746 4.032L4.503 29.275"></path>
</svg>
```

This change the SVG from looking like: 
<img width="54" alt="screen shot 2017-05-04 at 3 51 47 pm" src="https://cloud.githubusercontent.com/assets/791670/25722289/a34e354c-30e1-11e7-8ef5-33874ad03c2a.png">

To: 
<img width="41" alt="screen shot 2017-05-04 at 3 51 57 pm" src="https://cloud.githubusercontent.com/assets/791670/25722299/a9db7852-30e1-11e7-90a2-0ee3a0719eec.png">

**Comment by bcardarella** [comment]
Its likely svgo being too aggressive it its optimizations

**Comment by cory-tanner** [comment]
@bcardarella Not sure how I feel about svgo modifying svgs to the point that it effects how it renders on screen.

Is svgo required? I am leaning to the side of letting people optimize their own SVGs. Especially when people make their own SVGs from scratch, it would be annoying if a plugin changed what you developed.

**Comment by goodwinchris** [comment]
I'd mirror @Ctannerweb's thoughts.
