### ISSUE TITLE
`grid: true` not being respected as an autoprefixer option

### ISSUE THREAD

**Issue by cory-tanner** [dockyard/narwin-pack#21]
Autoprefixer is supposed to add `display: -ms-grid` for ie11. This is achieved with the rule `grid: true` under autoprefixers options in `ember-cli-build.js`. Not working unfortunately, I have also attempted adding it in narwin-packs `index.js` file. But still no luck.

**Comment by duggiefresh** [comment]
http://autoprefixer.github.io/
