### ISSUE TITLE
Add more flexible inline SVG plugin

### ISSUE THREAD

**Issue by cory-tanner** [dockyard/narwin-pack#5]
# Proposed plugin: [postcss-inline-svg](https://github.com/TrySound/postcss-inline-svg)
## Negatives:

This will introduce custom syntax that does not follow common CSS syntax.
## Benefit:

More SVG options when adding patters as background-images and variable like usage for each inline SVG used.

This plugin would replace postcss-svg-fragments

**Comment by bcardarella** [comment]
LOL, I didn't even realize I fixed this https://github.com/DockYard/narwin-pack/pull/9
